name = "imgbed"
compatibility_date = "2024-04-01"
pages_build_output_dir = "./"

# 绑定kv
[[kv_namespaces]]
binding = "img_url"
id = "783a3016d4eb4e5bb63aaf3c5a265919"

# R2 绑定
[[r2_buckets]]
binding = "img_r2"
bucket_name = "img-r2-bucket"
